//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DataLink.rc
//
#define IDS_STRING_DLGET                1
#define IDS_STRING_DLSET                2
#define IDS_STRING_DLFGET               3
#define IDS_STRING_DLFSET               4
#define IDS_STRING_DLRESET              5
#define IDS_STRING_DLGETSIZE            6
#define IDS_STRING_DLIGET               7
#define IDS_STRING_DLISET               8
#define IDS_STRING_DLIGETSIZE           9
#define IDS_STRING_DLWAIT               10
#define IDS_STRING_SUBKEY               100
#define IDS_STRING_GROUPKEY             101

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
